/-
Copyright (c) 2026.
Released under Apache 2.0 license as described in the file LICENSE.
-/

import Mathlib.Data.List.OfFn
import ComplexityReduction.Legacy.ComplexityReduction.SAT.CookLevin.FiniteAlphabet

/-!
Local-window grid generator for Cook-Levin finite-domain CSP encodings.

The existing `LocalWindowDescriptor` represents one local predicate over concrete
tableau atom references.  This module packages a finite list of such windows
under global time/cell/payload bounds and compiles it to the existing
`LocalPredicateFamily` finite-domain CSP formula.
-/

namespace ComplexityReduction
namespace SAT
namespace CookLevin
namespace TableauCSP

open ComplexityReduction.CSP.FiniteDomain

/--
Finite grid of local Cook-Levin windows.

Each local window may store its own conservative bounds; the grid descriptor
records proofs that those local bounds fit inside the global grid bounds and
that every referenced atom respects its local window bounds.
-/
structure WindowGridDescriptor where
  timeCount : Nat
  cellCount : Nat
  payloadCount : Nat
  windows : List LocalWindowDescriptor
  windowBounds :
    ∀ W ∈ windows, W.timeBound ≤ timeCount ∧ W.cellBound ≤ cellCount ∧
      W.payloadBound ≤ payloadCount
  referencesWithinBounds : ∀ W ∈ windows, W.ReferencesWithinBounds

namespace WindowGridDescriptor

/-- Local windows stored in the grid. -/
def localWindows (G : WindowGridDescriptor) : List LocalWindowDescriptor :=
  G.windows

/-- Atom references used by one local window. -/
def localAtomRefs (W : LocalWindowDescriptor) : List TableauAtomRef :=
  List.ofFn W.refs

/-- All tableau atom references used by the grid's local windows. -/
def atomRefs (G : WindowGridDescriptor) : List TableauAtomRef :=
  G.localWindows.flatMap localAtomRefs

/-- The local predicate family obtained by forgetting atom-reference metadata. -/
def localPredicateFamily (G : WindowGridDescriptor) : LocalPredicateFamily where
  blocks := G.localWindows.map LocalWindowDescriptor.block

/-- Assignment-level satisfaction of all generated grid windows. -/
def Satisfies (G : WindowGridDescriptor) (a : CSP.FiniteDomain.Assignment Bool) : Prop :=
  G.localPredicateFamily.Satisfies a

/-- Finite-domain CSP formula generated by all local windows in the grid. -/
def formula (G : WindowGridDescriptor) : Formula G.localPredicateFamily.language :=
  formulaOfPredicateFamily G.localPredicateFamily

/-- The generated grid formula is satisfied exactly when all local windows accept. -/
theorem formula_satisfies_iff (G : WindowGridDescriptor)
    (a : CSP.FiniteDomain.Assignment Bool) :
    Formula.Satisfies G.formula a ↔ G.Satisfies a := by
  simpa [formula, Satisfies] using
    formulaOfPredicateFamily_satisfies_iff G.localPredicateFamily a

/-- The generated grid formula has one constraint per local window. -/
theorem formula_length (G : WindowGridDescriptor) :
    G.formula.length = G.localWindows.length := by
  simp [formula, localPredicateFamily, formulaOfPredicateFamily, localWindows]

/-- Finite-support list for the generated grid formula. -/
noncomputable def supportList (G : WindowGridDescriptor) : List Nat :=
  G.localPredicateFamily.supportList

/-- Membership in the grid support list is membership in generated formula variables. -/
theorem mem_supportList (G : WindowGridDescriptor) (x : Nat) :
    x ∈ G.supportList ↔ x ∈ FiniteSupport.formulaVars G.formula := by
  classical
  simp [supportList, formula, formulaOfPredicateFamily]

/-- Every scoped variable in the generated family is below the grid formula variable bound. -/
theorem scope_lt_formulaVarBound (G : WindowGridDescriptor)
    (i : Fin G.localPredicateFamily.blocks.length)
    (j : Fin (G.localPredicateFamily.blocks.get i).predicate.arity) :
    (G.localPredicateFamily.blocks.get i).scope j <
      FiniteSupport.formulaVarBound G.formula := by
  simpa [formula] using
    formulaOfPredicateFamily_scope_lt_formulaVarBound G.localPredicateFamily i j

/-- Every atom reference listed by the grid is below the global time bound. -/
theorem ref_time_lt_of_mem (G : WindowGridDescriptor) {ref : TableauAtomRef}
    (href : ref ∈ G.atomRefs) :
    ref.time < G.timeCount := by
  rcases List.mem_flatMap.mp (by simpa [atomRefs] using href) with ⟨W, hW, hrefW⟩
  rcases List.mem_ofFn.mp (by simpa [localAtomRefs] using hrefW) with ⟨i, rfl⟩
  exact lt_of_lt_of_le
    (LocalWindowDescriptor.ref_time_lt_of_referencesWithinBounds W
      (G.referencesWithinBounds W (by simpa [localWindows] using hW)) i)
    (G.windowBounds W (by simpa [localWindows] using hW)).1

/-- Every atom reference listed by the grid is below the global cell bound. -/
theorem ref_cell_lt_of_mem (G : WindowGridDescriptor) {ref : TableauAtomRef}
    (href : ref ∈ G.atomRefs) :
    ref.cell < G.cellCount := by
  rcases List.mem_flatMap.mp (by simpa [atomRefs] using href) with ⟨W, hW, hrefW⟩
  rcases List.mem_ofFn.mp (by simpa [localAtomRefs] using hrefW) with ⟨i, rfl⟩
  exact lt_of_lt_of_le
    (LocalWindowDescriptor.ref_cell_lt_of_referencesWithinBounds W
      (G.referencesWithinBounds W (by simpa [localWindows] using hW)) i)
    (G.windowBounds W (by simpa [localWindows] using hW)).2.1

/-- Every atom reference listed by the grid is below the global payload bound. -/
theorem ref_payload_lt_of_mem (G : WindowGridDescriptor) {ref : TableauAtomRef}
    (href : ref ∈ G.atomRefs) :
    ref.payload < G.payloadCount := by
  rcases List.mem_flatMap.mp (by simpa [atomRefs] using href) with ⟨W, hW, hrefW⟩
  rcases List.mem_ofFn.mp (by simpa [localAtomRefs] using hrefW) with ⟨i, rfl⟩
  exact lt_of_lt_of_le
    (LocalWindowDescriptor.ref_payload_lt_of_referencesWithinBounds W
      (G.referencesWithinBounds W (by simpa [localWindows] using hW)) i)
    (G.windowBounds W (by simpa [localWindows] using hW)).2.2

end WindowGridDescriptor

end TableauCSP
end CookLevin
end SAT
end ComplexityReduction
