/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/

import ComplexityReduction.Legacy.ComplexityReduction.Core.NPClass
import ComplexityReduction.Legacy.ComplexityReduction.Core.ProblemEquiv

namespace ComplexityReduction

/-- A named class of encoded decision problems closed under a reduction model. -/
structure ComplexityClass (M : PolyTimeModel) where
  mem : EncodedDecisionProblem → Prop
  of_reduction :
    {A B : EncodedDecisionProblem} →
      PolyReducibleM M A B → mem B → mem A

namespace ComplexityClass

/-- The class generated by NP verifiers and reduction closure. -/
def NP (M : PolyTimeModel) : ComplexityClass M where
  mem := InNPEnc M
  of_reduction := InNPEnc.of_reduction

end ComplexityClass

/-- Completeness for an arbitrary encoded class under a reduction model. -/
def CompleteFor (M : PolyTimeModel) (C : ComplexityClass M) (L : EncodedDecisionProblem) :
    Prop :=
  C.mem L ∧ ∀ L', C.mem L' → PolyReducibleM M L' L

namespace CompleteFor

/-- Transfer completeness across a many-one reduction. -/
theorem transfer {M : PolyTimeModel} {C : ComplexityClass M}
    {A B : EncodedDecisionProblem}
    (hA : CompleteFor M C A) (hRed : PolyReducibleM M A B) (hB : C.mem B) :
    CompleteFor M C B := by
  constructor
  · exact hB
  · intro L hL
    exact PolyReducibleM.trans (hA.2 L hL) hRed

/-- Transport completeness across a polynomial-time problem equivalence. -/
theorem congr_problemEquiv {M : PolyTimeModel} {C : ComplexityClass M}
    {A B : EncodedDecisionProblem}
    (e : ProblemEquivM M A B) :
    CompleteFor M C A ↔ CompleteFor M C B := by
  constructor
  · intro hA
    have hB : C.mem B := C.of_reduction e.invReducible hA.1
    exact transfer hA e.toReducible hB
  · intro hB
    have hA : C.mem A := C.of_reduction e.toReducible hB.1
    exact transfer hB e.invReducible hA

end CompleteFor

namespace InP

/-- `P` is invariant under polynomial-time problem equivalence. -/
theorem congr_problemEquiv {M : PolyTimeModel} {A B : EncodedDecisionProblem}
    (e : ProblemEquivM M A B) :
    InP M A ↔ InP M B := by
  constructor
  · intro hA
    exact InP.of_reduction e.invReducible hA
  · intro hB
    exact InP.of_reduction e.toReducible hB

end InP

namespace InNPEnc

/-- Encoded NP membership is invariant under polynomial-time problem equivalence. -/
theorem congr_problemEquiv {M : PolyTimeModel} {A B : EncodedDecisionProblem}
    (e : ProblemEquivM M A B) :
    InNPEnc M A ↔ InNPEnc M B := by
  constructor
  · intro hA
    exact InNPEnc.of_reduction e.invReducible hA
  · intro hB
    exact InNPEnc.of_reduction e.toReducible hB

end InNPEnc

namespace NPCompleteEnc

/-- Named specialization of `transfer` for a complete source and a reduction to a target. -/
theorem of_complete_source_reduction {M : PolyTimeModel} {A B : EncodedDecisionProblem}
    (hA : NPCompleteEnc M A)
    (hRed : PolyReducibleM M A B)
    (hB : InNPEnc M B) :
    NPCompleteEnc M B :=
  transfer hA hRed hB

/-- NP-completeness is invariant under polynomial-time problem equivalence. -/
theorem congr_problemEquiv {M : PolyTimeModel} {A B : EncodedDecisionProblem}
    (e : ProblemEquivM M A B) :
    NPCompleteEnc M A ↔ NPCompleteEnc M B := by
  constructor
  · intro hA
    have hBInNP : InNPEnc M B := (InNPEnc.congr_problemEquiv e).1 hA.1
    exact transfer hA e.toReducible hBInNP
  · intro hB
    have hAInNP : InNPEnc M A := (InNPEnc.congr_problemEquiv e).2 hB.1
    exact transfer hB e.invReducible hAInNP

end NPCompleteEnc

end ComplexityReduction
