/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/

import ComplexityReduction.Legacy.ComplexityReduction.Core.Reduction
import ComplexityReduction.Legacy.ComplexityReduction.Certificates.CostedMap
import ComplexityReduction.Legacy.ComplexityReduction.SAT.ThreeSAT

namespace ComplexityReduction

/-- A verifier over encoded instances and encoded certificates. -/
structure NPVerifier (M : PolyTimeModel) (L : EncodedDecisionProblem) where
  Cert : EncodedType
  verify : L.Instance.Carrier → Cert.Carrier → Bool
  verifier_polytime :
    M.IsPolyTimeMap (X := EncodedType.prod L.Instance Cert) (Y := EncodedType.bool)
      (fun p => verify p.1 p.2)
  cert_bound :
    ∃ degree coeff const : Nat,
      ∀ x, L.isYes x →
        ∃ c, Cert.inputSize c ≤
          coeff * (L.Instance.inputSize x) ^ degree + const ∧
          verify x c = true
  sound : ∀ x c, verify x c = true → L.isYes x

namespace NPVerifier

/-- A direct verifier is correct after forgetting the certificate size bound. -/
theorem correct_iff {M : PolyTimeModel} {L : EncodedDecisionProblem}
    (V : NPVerifier M L) (x : L.Instance.Carrier) :
    L.isYes x ↔ ∃ c, V.verify x c = true := by
  constructor
  · intro hx
    rcases V.cert_bound with ⟨degree, coeff, const, hBound⟩
    rcases hBound x hx with ⟨c, _hSize, hVerify⟩
    exact ⟨c, hVerify⟩
  · intro h
    rcases h with ⟨c, hVerify⟩
    exact V.sound x c hVerify

end NPVerifier

/--
A local verifier witness whose direct introduction is already accompanied by a
syntactic Cook-Levin map to the bundled local 3SAT target.

The legacy `NPVerifier` remains available below, but the main local `InNPEnc`
class no longer accepts an opaque Lean verifier as a leaf.
-/
structure LocalNPVerifier (M : PolyTimeModel) (L : EncodedDecisionProblem) where
  verifier : NPVerifier M L
  cookTableauThreeCNF : L.Instance.Carrier → SAT.ThreeCNF
  cookTableauThreeCNF_polytime :
    M.IsPolyTimeMap
      (X := L.Instance) (Y := SAT.threeSATDecisionProblem.Instance)
      cookTableauThreeCNF
  cookTableauThreeCNF_correct :
    ∀ x, L.isYes x ↔ SAT.ThreeCNF.Satisfiable (cookTableauThreeCNF x)

namespace LocalNPVerifier

/-- View the local verifier witness as a Karp reduction to local 3SAT. -/
def toKarpReduction {M : PolyTimeModel} {L : EncodedDecisionProblem}
    (V : LocalNPVerifier M L) :
    KarpReductionM M L SAT.threeSATDecisionProblem where
  f := { toFun := V.cookTableauThreeCNF, polytime := V.cookTableauThreeCNF_polytime }
  correct := by
    intro x
    exact V.cookTableauThreeCNF_correct x

end LocalNPVerifier

/--
Legacy encoded NP, generated by opaque direct verifiers and closed under
reductions.  This is kept for compatibility/audit only; local Cook-Levin
theorems do not silently consume this class.
-/
inductive LegacyInNPEnc (M : PolyTimeModel) : EncodedDecisionProblem → Prop
  | of_verifier {L : EncodedDecisionProblem} (V : NPVerifier M L) : LegacyInNPEnc M L
  | reduction_closure {A B : EncodedDecisionProblem}
      (hAB : PolyReducibleM M A B) (hB : LegacyInNPEnc M B) : LegacyInNPEnc M A

namespace LegacyInNPEnc

/-- Build legacy encoded NP membership from an explicit opaque verifier. -/
theorem intro {M : PolyTimeModel} {L : EncodedDecisionProblem} (V : NPVerifier M L) :
    LegacyInNPEnc M L :=
  LegacyInNPEnc.of_verifier V

/-- Legacy encoded NP is downward closed under model-level reductions. -/
theorem of_reduction {M : PolyTimeModel} {A B : EncodedDecisionProblem}
    (hAB : PolyReducibleM M A B) (hB : LegacyInNPEnc M B) :
    LegacyInNPEnc M A :=
  LegacyInNPEnc.reduction_closure hAB hB

end LegacyInNPEnc

/--
Locally verified encoded NP.  Direct leaves must carry a Cook-Levin-style
syntax map to local 3SAT; arbitrary opaque `NPVerifier` values are represented
only by `LegacyInNPEnc`.
-/
inductive InNPEnc (M : PolyTimeModel) : EncodedDecisionProblem → Prop
  | of_local_verifier {L : EncodedDecisionProblem} (V : LocalNPVerifier M L) :
      InNPEnc M L
  | reduction_closure {A B : EncodedDecisionProblem}
      (hAB : PolyReducibleM M A B) (hB : InNPEnc M B) :
      InNPEnc M A

namespace InNPEnc

/-- Build local encoded NP membership from a Cook-Levin-backed verifier witness. -/
theorem intro {M : PolyTimeModel} {L : EncodedDecisionProblem} (V : LocalNPVerifier M L) :
    InNPEnc M L :=
  InNPEnc.of_local_verifier V

/-- Encoded NP is downward closed under model-level reductions. -/
theorem of_reduction {M : PolyTimeModel} {A B : EncodedDecisionProblem}
    (hAB : PolyReducibleM M A B) (hB : InNPEnc M B) :
    InNPEnc M A :=
  InNPEnc.reduction_closure hAB hB

/-- Forget locally verified encoded NP membership to the legacy opaque class. -/
theorem toLegacy {M : PolyTimeModel} {L : EncodedDecisionProblem} (hL : InNPEnc M L) :
    LegacyInNPEnc M L := by
  induction hL with
  | of_local_verifier V =>
      exact LegacyInNPEnc.of_verifier V.verifier
  | reduction_closure hAB _ ih =>
      exact LegacyInNPEnc.of_reduction hAB ih

end InNPEnc

/-- Encoded NP-hardness under a chosen polynomial-time reduction model. -/
def NPHardEnc (M : PolyTimeModel) (L : EncodedDecisionProblem) : Prop :=
  ∀ L', InNPEnc M L' → PolyReducibleM M L' L

/-- Encoded NP-completeness under a chosen polynomial-time reduction model. -/
def NPCompleteEnc (M : PolyTimeModel) (L : EncodedDecisionProblem) : Prop :=
  InNPEnc M L ∧ NPHardEnc M L

namespace NPHardEnc

/-- NP-hardness transfers forward along a model-level many-one reduction. -/
theorem transfer {M : PolyTimeModel} {A B : EncodedDecisionProblem}
    (hA : NPHardEnc M A)
    (hRed : PolyReducibleM M A B) :
    NPHardEnc M B := by
  intro L hL
  exact PolyReducibleM.trans (hA L hL) hRed

/-- A complete source plus a reduction to the target proves target NP-hardness. -/
theorem of_complete_source {M : PolyTimeModel} {A B : EncodedDecisionProblem}
    (hA : NPCompleteEnc M A)
    (hRed : PolyReducibleM M A B) :
    NPHardEnc M B :=
  transfer hA.2 hRed

end NPHardEnc

namespace NPCompleteEnc

/-- Transfer NP-completeness across a model-level many-one reduction. -/
theorem transfer {M : PolyTimeModel} {A B : EncodedDecisionProblem}
    (hA : NPCompleteEnc M A)
    (hRed : PolyReducibleM M A B)
    (hB : InNPEnc M B) :
    NPCompleteEnc M B := by
  constructor
  · exact hB
  · exact NPHardEnc.transfer hA.2 hRed

theorem mem_np {M : PolyTimeModel} {L : EncodedDecisionProblem}
    (h : NPCompleteEnc M L) : InNPEnc M L :=
  h.1

theorem hard {M : PolyTimeModel} {L : EncodedDecisionProblem}
    (h : NPCompleteEnc M L) (L' : EncodedDecisionProblem) (hL' : InNPEnc M L') :
    PolyReducibleM M L' L :=
  h.2 L' hL'

/-- Forget NP-completeness to the explicit NP-hardness track. -/
theorem hardness {M : PolyTimeModel} {L : EncodedDecisionProblem}
    (h : NPCompleteEnc M L) : NPHardEnc M L :=
  h.2

end NPCompleteEnc

/-- Compatibility name for legacy raw encoded NP membership. -/
abbrev RawInNP (L : DecisionProblem) : Prop :=
  InNPEnc ClosurePolyTimeModel L.withRawEncoding

/-- Compatibility name for legacy raw encoded NP-completeness. -/
abbrev NPComplete (L : DecisionProblem) : Prop :=
  NPCompleteEnc ClosurePolyTimeModel L.withRawEncoding

end ComplexityReduction
