import ComplexityReduction.Legacy.ComplexityReduction.Karp21.SetPacking.Base
import ComplexityReduction.Legacy.ComplexityReduction.Karp21.SetPacking.StructuredRoute
import ComplexityReduction.Legacy.ComplexityReduction.Karp21.SetPacking.TMRoute
import ComplexityReduction.Legacy.ComplexityReduction.Karp21.SetPacking.StructuredTMRoute
