/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/

import ComplexityReduction.Legacy.ComplexityReduction.Certificates.StrictLogSpaceMap

/-!
Project-local strict streaming certificates.

`StrictStreamMap` refines the strict log-space layer with small, auditable
streaming combinators.  It is still a project-level certificate DSL: turning it
into machine semantics is intentionally delegated to an explicit bridge theorem.
The important invariant is the same as for `StrictLogSpaceMap`: there is no
constructor from an arbitrary costed map.
-/

namespace ComplexityReduction

/-- Human-auditable metadata for a strict streaming primitive. -/
structure StrictStreamPrimitive (X Y : EncodedType) (f : X.Carrier → Y.Carrier) where
  name : String
  pass_bound : String
  workspace_bound : String
  output_order : String
  oracle_free : String
  costed : CostedPolyTimeMap (X := X) (Y := Y) f
  deriving Repr

/-- Strict streaming maps generated by compositional list/constructor primitives. -/
inductive StrictStreamMap : {X Y : EncodedType} → (X.Carrier → Y.Carrier) → Prop
  | id_map {X : EncodedType} :
      StrictStreamMap (X := X) (Y := X) id
  | comp_map {X Y Z : EncodedType} {f : Y.Carrier → Z.Carrier}
      {g : X.Carrier → Y.Carrier}
      (hf : StrictStreamMap f) (hg : StrictStreamMap g) :
      StrictStreamMap (f ∘ g)
  | const_map {X Y : EncodedType} (y : Y.Carrier) :
      StrictStreamMap (X := X) (Y := Y) (fun _ => y)
  | fst_map {X Y : EncodedType} :
      StrictStreamMap (X := EncodedType.prod X Y) (Y := X)
        (@Prod.fst X.Carrier Y.Carrier)
  | snd_map {X Y : EncodedType} :
      StrictStreamMap (X := EncodedType.prod X Y) (Y := Y)
        (@Prod.snd X.Carrier Y.Carrier)
  | prod_mk_map {X Y Z : EncodedType} {f : X.Carrier → Y.Carrier}
      {g : X.Carrier → Z.Carrier}
      (hf : StrictStreamMap f) (hg : StrictStreamMap g) :
      StrictStreamMap (X := X) (Y := EncodedType.prod Y Z) (fun x => (f x, g x))
  | inl_map {X Y : EncodedType} :
      StrictStreamMap (X := X) (Y := EncodedType.sum X Y) (@Sum.inl X.Carrier Y.Carrier)
  | inr_map {X Y : EncodedType} :
      StrictStreamMap (X := Y) (Y := EncodedType.sum X Y) (@Sum.inr X.Carrier Y.Carrier)
  | list_map_map {X Y : EncodedType} {f : X.Carrier → Y.Carrier}
      (hf : StrictStreamMap f) :
      StrictStreamMap (X := EncodedType.list X) (Y := EncodedType.list Y)
        (fun xs => xs.map f)
  | list_flatMap_constBound {X Y : EncodedType} {f : X.Carrier → List Y.Carrier}
      (hf : StrictStreamMap (X := X) (Y := EncodedType.list Y) f)
      (block_bound : Nat)
      (hcosted : CostedPolyTimeMap (X := EncodedType.list X) (Y := EncodedType.list Y)
        (fun xs => xs.flatMap f)) :
      StrictStreamMap (X := EncodedType.list X) (Y := EncodedType.list Y)
        (fun xs => xs.flatMap f)
  | list_append_map {X : EncodedType} :
      StrictStreamMap
        (X := EncodedType.prod (EncodedType.list X) (EncodedType.list X))
        (Y := EncodedType.list X)
        (fun p : List X.Carrier × List X.Carrier => p.1 ++ p.2)
  | list_foldl_map {X Y : EncodedType} {step : Y.Carrier × X.Carrier → Y.Carrier}
      (hstep : StrictStreamMap (X := EncodedType.prod Y X) (Y := Y) step)
      (init : Y.Carrier) :
      StrictStreamMap (X := EncodedType.list X) (Y := Y)
        (fun xs => xs.foldl (fun acc x => step (acc, x)) init)
  | registeredPrimitive {X Y : EncodedType} {f : X.Carrier → Y.Carrier}
      (p : StrictStreamPrimitive X Y f) :
      StrictStreamMap (X := X) (Y := Y) f

namespace StrictStreamMap

/-- Every strict streaming certificate exposes a strict log-space certificate. -/
theorem toStrictLogSpaceMap {X Y : EncodedType} {f : X.Carrier → Y.Carrier}
    (h : StrictStreamMap (X := X) (Y := Y) f) :
    StrictLogSpaceMap (X := X) (Y := Y) f := by
  induction h with
  | id_map => exact StrictLogSpaceMap.id_map
  | comp_map hf hg ihf ihg => exact StrictLogSpaceMap.comp_map ihf ihg
  | const_map y => exact StrictLogSpaceMap.const_map y
  | fst_map => exact StrictLogSpaceMap.fst_map
  | snd_map => exact StrictLogSpaceMap.snd_map
  | prod_mk_map hf hg ihf ihg => exact StrictLogSpaceMap.prod_mk_map ihf ihg
  | inl_map => exact StrictLogSpaceMap.inl_map
  | inr_map => exact StrictLogSpaceMap.inr_map
  | list_map_map hf ih => exact StrictLogSpaceMap.list_map_map ih
  | list_flatMap_constBound hf block_bound hcosted ih =>
      exact StrictLogSpaceMap.registeredPrimitive
        { name := "list.flatMap.constBound"
          construction :=
            "Stream the input list left-to-right and emit each certified bounded block."
          space_bound :=
            "Project-local O(log |input|) counters plus the constant-size emitted block."
          oracle_free := "The iterator uses only the input list and the certified element map."
          costed := hcosted }
  | list_append_map => exact StrictLogSpaceMap.list_append_map
  | list_foldl_map hstep init ih => exact StrictLogSpaceMap.list_foldl_map ih init
  | registeredPrimitive p =>
      exact StrictLogSpaceMap.registeredPrimitive
        { name := p.name
          construction := p.pass_bound ++ "; " ++ p.output_order
          space_bound := p.workspace_bound
          oracle_free := p.oracle_free
          costed := p.costed }

/-- Every strict streaming certificate also has project-local costed polytime metadata. -/
theorem toCostedPolyTimeMap {X Y : EncodedType} {f : X.Carrier → Y.Carrier}
    (h : StrictStreamMap (X := X) (Y := Y) f) :
    CostedPolyTimeMap (X := X) (Y := Y) f :=
  h.toStrictLogSpaceMap.toCostedPolyTimeMap

end StrictStreamMap

end ComplexityReduction
