/-
Copyright (c) 2026.
Released under Apache 2.0 license as described in the file LICENSE.
-/

import Mathlib.Data.Fintype.BigOperators
import Mathlib.Algebra.Order.BigOperators.Group.List
import ComplexityReduction.Legacy.ComplexityReduction.Certificates
import ComplexityReduction.Legacy.ComplexityReduction.CSP.To3SAT
import ComplexityReduction.Legacy.ComplexityReduction.SAT.CNFTo3SATCosted

/-!
Size facts for the Boolean-CSP-to-3SAT map.

The semantic reduction lives in `ComplexityReduction.CSP.To3SAT`.  This file
starts the separate complexity-certificate layer: it exposes concrete encoding
length lemmas and the fixed arity-3 bound on the number of clauses generated by
one constraint.
-/

namespace ComplexityReduction
namespace CSP

open SAT

namespace Encoding

@[simp]
theorem encodeNat_length {Γ : BoolLanguage} (n : Nat) :
    (encodeNat (Γ := Γ) n).length = n + 1 := by
  simp [encodeNat, EncodedType.nat]

@[simp]
theorem encodeVar_length {Γ : BoolLanguage} (n : Nat) :
    (encodeVar (Γ := Γ) n).length = n + 2 := by
  simp [encodeVar, encodeNat, EncodedType.nat]

theorem encodeConstraint_length {Γ : BoolLanguage} (c : Constraint Γ) :
    (encodeConstraint c).length =
      2 + ((List.ofFn c.vars).map fun n => n + 2).sum := by
  have hsum :
      (List.ofFn ((fun a => a + 1 + 1) ∘ c.vars)).sum =
        (List.ofFn ((fun n => n + 2) ∘ c.vars)).sum := by
    congr 2
  simp [encodeConstraint, encodeVar, encodeNat, EncodedType.nat, List.length_flatMap]
  rw [hsum]
  omega

@[simp]
theorem encodeFormula_length_cons {Γ : BoolLanguage} (c : Constraint Γ) (φ : Formula Γ) :
    (encodeFormula (c :: φ)).length = (encodeConstraint c).length + (encodeFormula φ).length := by
  simp [encodeFormula]

end Encoding

end CSP

namespace SAT
namespace ThreeSATEncoding

@[simp]
theorem encodeNat_length (n : Nat) :
    (encodeNat n).length = n + 1 := by
  simp [encodeNat, EncodedType.nat]

@[simp]
theorem encodeLiteral_length (l : Literal) :
    (encodeLiteral l).length = l.var + 6 := by
  simp [encodeLiteral, encodeNat, EncodedType.nat]

theorem encodeClauseForTuple_length {k : Nat} (vars : Fin k → Nat)
    (t : CSP.BoolTuple k) :
    (encodeClause (CSP.clauseForTuple vars t)).length =
      1 + ((List.ofFn vars).map fun n => n + 6).sum := by
  have hsum :
      (List.ofFn
          ((fun a : Literal => a.var + 1 + 1 + 1 + 1 + 1 + 1) ∘
            fun i => ({ var := vars i, neg := t i } : Literal))).sum =
        (List.ofFn ((fun n => n + 6) ∘ vars)).sum := by
    congr 2
  simp [encodeClause, CSP.clauseForTuple, CSP.literalForTuple, encodeLiteral, encodeNat,
    EncodedType.nat, List.length_flatMap]
  rw [hsum]
  omega

end ThreeSATEncoding
end SAT

namespace CSP

namespace ListBounds

theorem sum_map_le_length_mul {α : Type} (l : List α) (f : α → Nat) (B : Nat)
    (h : ∀ x ∈ l, f x ≤ B) :
    (l.map f).sum ≤ l.length * B := by
  induction l with
  | nil => simp
  | cons x xs ih =>
      have hx : f x ≤ B := h x (by simp)
      have hxs : (xs.map f).sum ≤ xs.length * B := ih (by
        intro y hy
        exact h y (by simp [hy]))
      simp
      rw [Nat.succ_mul]
      omega

theorem sum_add_six_le_three_sum_add_two (l : List Nat) :
    (l.map fun n => n + 6).sum ≤ 3 * (2 + (l.map fun n => n + 2).sum) := by
  induction l with
  | nil => simp
  | cons a as ih =>
      simp [List.sum_map_add] at ih ⊢
      omega

end ListBounds

namespace Constraint

/-- A 3-bounded relation has at most eight falsifying tuples. -/
theorem falsifyingTuple_count_le_eight {Γ : BoolLanguage} (hΓ : Γ.IsThreeBounded)
    (c : Constraint Γ) :
    c.relation.falsifyingTuples.toList.length ≤ 8 := by
  classical
  have hcard : c.relation.falsifyingTuples.card ≤ Fintype.card (BoolTuple c.relation.arity) :=
    Finset.card_le_univ _
  have htuple : Fintype.card (BoolTuple c.relation.arity) ≤ 8 := by
    rw [Fintype.card_pi_const Bool c.relation.arity, Fintype.card_bool]
    exact (Nat.pow_le_pow_right (by decide : 0 < 2) (hΓ c.symbol)).trans (by decide)
  rw [Finset.length_toList]
  exact hcard.trans htuple

/--
The number of clauses generated by one 3-bounded CSP constraint is bounded by a
fixed constant. This is the local combinatorial fact needed by the final size
certificate.
-/
theorem toCNF_length_le_eight {Γ : BoolLanguage} (hΓ : Γ.IsThreeBounded)
    (c : Constraint Γ) :
    (Constraint.toCNF c).length ≤ 8 := by
  rw [Constraint.toCNF, List.length_map]
  exact falsifyingTuple_count_le_eight hΓ c

theorem encodedClause_length_le {Γ : BoolLanguage} (c : Constraint Γ)
    (cl : SAT.Clause) (hcl : cl ∈ Constraint.toCNF c) :
    (SAT.ThreeSATEncoding.encodeClause cl).length ≤
      1 + 3 * (Encoding.encodeConstraint c).length := by
  rw [Constraint.toCNF] at hcl
  rcases List.mem_map.1 hcl with ⟨t, _ht, rfl⟩
  rw [SAT.ThreeSATEncoding.encodeClauseForTuple_length]
  have hvars :
      ((List.ofFn c.vars).map fun n => n + 6).sum ≤
        3 * (Encoding.encodeConstraint c).length := by
    rw [Encoding.encodeConstraint_length]
    exact ListBounds.sum_add_six_le_three_sum_add_two (List.ofFn c.vars)
  omega

theorem encodedBlock_length_le {Γ : BoolLanguage} (hΓ : Γ.IsThreeBounded)
    (c : Constraint Γ) :
    ((Constraint.toCNF c).map fun cl => (SAT.ThreeSATEncoding.encodeClause cl).length).sum ≤
      28 * (Encoding.encodeConstraint c).length := by
  have hEach :
      ∀ cl ∈ Constraint.toCNF c,
        (SAT.ThreeSATEncoding.encodeClause cl).length ≤
          1 + 3 * (Encoding.encodeConstraint c).length := by
    intro cl hcl
    exact encodedClause_length_le c cl hcl
  have hsum :=
    ListBounds.sum_map_le_length_mul
      (Constraint.toCNF c)
      (fun cl => (SAT.ThreeSATEncoding.encodeClause cl).length)
      (1 + 3 * (Encoding.encodeConstraint c).length)
      hEach
  have hlen := Constraint.toCNF_length_le_eight hΓ c
  have henc : 2 ≤ (Encoding.encodeConstraint c).length := by
    rw [Encoding.encodeConstraint_length]
    omega
  have hsum8 :
      ((Constraint.toCNF c).map fun cl => (SAT.ThreeSATEncoding.encodeClause cl).length).sum ≤
        8 * (1 + 3 * (Encoding.encodeConstraint c).length) := by
    exact hsum.trans (Nat.mul_le_mul_right _ hlen)
  omega

end Constraint

namespace Formula

theorem toThreeCNF_encodedLength_le {Γ : BoolLanguage} (hΓ : Γ.IsThreeBounded)
    (φ : Formula Γ) :
    (SAT.ThreeSATEncoding.encodeThreeCNF (Formula.toThreeCNF hΓ φ)).length ≤
      28 * (Encoding.encodeFormula φ).length := by
  induction φ with
  | nil =>
      simp [Formula.toThreeCNF, Formula.toCNF, SAT.CNF.toThreeCNF,
        SAT.ThreeSATEncoding.encodeThreeCNF, Encoding.encodeFormula]
  | cons c cs ih =>
      have hc := Constraint.encodedBlock_length_le hΓ c
      have hcs :
          (List.map (fun a => (SAT.ThreeSATEncoding.encodeClause a).length)
              (Formula.toCNF cs)).sum ≤
            28 * (List.map (fun a => (Encoding.encodeConstraint a).length) cs).sum := by
        simpa [Formula.toThreeCNF, SAT.CNF.toThreeCNF,
          SAT.ThreeSATEncoding.encodeThreeCNF, Encoding.encodeFormula, List.length_flatMap] using ih
      simp [Formula.toThreeCNF, Formula.toCNF, SAT.CNF.toThreeCNF,
        SAT.ThreeSATEncoding.encodeThreeCNF, Encoding.encodeFormula, List.length_flatMap]
      omega

theorem toThreeCNF_linearSizeBound {Γ : BoolLanguage} (hΓ : Γ.IsThreeBounded) :
    LinearSizeBound
      (fun φ : Formula Γ => (boolCSPDecisionProblem Γ).Instance.inputSize φ)
      (fun ψ : SAT.ThreeCNF => SAT.threeSATDecisionProblem.Instance.inputSize ψ)
      (fun φ => Formula.toThreeCNF hΓ φ) :=
  LinearSizeBound.intro_with 28 0 (by
    intro φ
    simpa [EncodedType.inputSize, boolCSPDecisionProblem, boolCSPSatLike,
      formulaEncodedType, SAT.threeSATDecisionProblem, SAT.threeSATSatLike,
      SAT.threeCNFEncodedType]
      using Formula.toThreeCNF_encodedLength_le hΓ φ)

end Formula

namespace Constraint

/-- For a fixed finite language, one constraint produces at most the language-wide
maximum number of falsifying tuples. -/
theorem toCNF_length_le_maxFalsifyingTuples {Γ : BoolLanguage} (c : Constraint Γ) :
    (Constraint.toCNF c).length ≤ Γ.maxFalsifyingTuples := by
  rw [Constraint.toCNF, List.length_map]
  have hlen :
      c.relation.falsifyingTuples.toList.length = c.relation.falsifyingTuples.card :=
    Finset.length_toList _
  have hcard := Γ.falsifyingTuples_card_le_maxFalsifyingTuples c.symbol
  exact hlen.trans_le (by simpa [Constraint.relation] using hcard)

/-- Every clause generated by one constraint has length bounded by the language-wide arity. -/
theorem toCNF_clause_length_le_maxArity {Γ : BoolLanguage} (c : Constraint Γ)
    (cl : SAT.Clause) (hcl : cl ∈ Constraint.toCNF c) :
    cl.length ≤ Γ.maxArity := by
  rw [Constraint.toCNF] at hcl
  rcases List.mem_map.1 hcl with ⟨t, _ht, rfl⟩
  simpa [clauseForTuple, Constraint.relation] using Γ.arity_le_maxArity c.symbol

/-- Total local CNF literal count for one constraint is language-constant bounded. -/
theorem toCNF_totalClauseLength_le_max {Γ : BoolLanguage} (c : Constraint Γ) :
    SAT.CNF.totalClauseLength (Constraint.toCNF c) ≤
      Γ.maxFalsifyingTuples * Γ.maxArity := by
  have hEach :
      ∀ cl ∈ Constraint.toCNF c, cl.length ≤ Γ.maxArity :=
    toCNF_clause_length_le_maxArity c
  have hsum :=
    ListBounds.sum_map_le_length_mul
      (Constraint.toCNF c)
      (fun cl => cl.length)
      Γ.maxArity
      hEach
  have hlen := toCNF_length_le_maxFalsifyingTuples c
  rw [SAT.CNF.totalClauseLength_eq_sum_length]
  exact hsum.trans (Nat.mul_le_mul_right Γ.maxArity hlen)

/-- Variables emitted by the local truth-table expansion already occur in the source constraint. -/
theorem toCNF_lit_var_lt_encodeConstraint_length {Γ : BoolLanguage}
    (c : Constraint Γ) (cl : SAT.Clause) (hcl : cl ∈ Constraint.toCNF c)
    (l : SAT.Literal) (hl : l ∈ cl) :
    l.var < (Encoding.encodeConstraint c).length := by
  rw [Constraint.toCNF] at hcl
  rcases List.mem_map.1 hcl with ⟨t, _ht, rfl⟩
  rcases (List.mem_ofFn' (fun i : Fin c.relation.arity => literalForTuple c.vars t i) l).1
      hl with ⟨i, rfl⟩
  rw [Encoding.encodeConstraint_length]
  change c.vars i < 2 + ((List.ofFn c.vars).map fun n => n + 2).sum
  have hmem :
      c.vars i + 2 ∈ (List.ofFn c.vars).map (fun n => n + 2) := by
    exact List.mem_map.mpr ⟨c.vars i, List.mem_ofFn.2 ⟨i, rfl⟩, rfl⟩
  have hle : c.vars i + 2 ≤ ((List.ofFn c.vars).map fun n => n + 2).sum :=
    List.le_sum_of_mem hmem
  omega

end Constraint

namespace Formula

/-- CNF block count grows linearly for every fixed finite Boolean CSP language. -/
theorem toCNF_length_le_general {Γ : BoolLanguage} (φ : Formula Γ) :
    (Formula.toCNF φ).length ≤ Γ.maxFalsifyingTuples * (Encoding.encodeFormula φ).length := by
  induction φ with
  | nil =>
      simp [Formula.toCNF, Encoding.encodeFormula]
  | cons c cs ih =>
      have hc := Constraint.toCNF_length_le_maxFalsifyingTuples c
      have henc : 1 ≤ (Encoding.encodeConstraint c).length := by
        rw [Encoding.encodeConstraint_length]
        omega
      rw [Formula.toCNF_cons, List.length_append, Encoding.encodeFormula_length_cons]
      have hfirst :
          Γ.maxFalsifyingTuples ≤
            Γ.maxFalsifyingTuples * (Encoding.encodeConstraint c).length := by
        simpa using Nat.mul_le_mul_left Γ.maxFalsifyingTuples henc
      calc
        (Constraint.toCNF c).length + (Formula.toCNF cs).length
            ≤ Γ.maxFalsifyingTuples +
                Γ.maxFalsifyingTuples * (Encoding.encodeFormula cs).length :=
          Nat.add_le_add hc ih
        _ ≤ Γ.maxFalsifyingTuples * (Encoding.encodeConstraint c).length +
            Γ.maxFalsifyingTuples * (Encoding.encodeFormula cs).length :=
          Nat.add_le_add_right hfirst _
        _ = Γ.maxFalsifyingTuples *
            ((Encoding.encodeConstraint c).length + (Encoding.encodeFormula cs).length) := by
          rw [Nat.mul_add]

/-- Total generated literal count grows linearly for every fixed finite Boolean CSP language. -/
theorem toCNF_totalClauseLength_le_general {Γ : BoolLanguage} (φ : Formula Γ) :
    SAT.CNF.totalClauseLength (Formula.toCNF φ) ≤
      (Γ.maxFalsifyingTuples * Γ.maxArity) * (Encoding.encodeFormula φ).length := by
  induction φ with
  | nil =>
      simp [Formula.toCNF, Encoding.encodeFormula, SAT.CNF.totalClauseLength]
  | cons c cs ih =>
      have hc := Constraint.toCNF_totalClauseLength_le_max c
      have henc : 1 ≤ (Encoding.encodeConstraint c).length := by
        rw [Encoding.encodeConstraint_length]
        omega
      rw [Formula.toCNF_cons, SAT.CNF.totalClauseLength_append, Encoding.encodeFormula_length_cons]
      let K := Γ.maxFalsifyingTuples * Γ.maxArity
      have hfirst : K ≤ K * (Encoding.encodeConstraint c).length := by
        simpa using Nat.mul_le_mul_left K henc
      calc
        SAT.CNF.totalClauseLength (Constraint.toCNF c) +
            SAT.CNF.totalClauseLength (Formula.toCNF cs)
            ≤ K + K * (Encoding.encodeFormula cs).length :=
          Nat.add_le_add hc ih
        _ ≤ K * (Encoding.encodeConstraint c).length +
            K * (Encoding.encodeFormula cs).length :=
          Nat.add_le_add_right hfirst _
        _ = K * ((Encoding.encodeConstraint c).length + (Encoding.encodeFormula cs).length) := by
          rw [Nat.mul_add]

theorem toCNF_lit_var_lt_encodeFormula_length {Γ : BoolLanguage}
    (φ : Formula Γ) (cl : SAT.Clause) (hcl : cl ∈ Formula.toCNF φ)
    (l : SAT.Literal) (hl : l ∈ cl) :
    l.var < (Encoding.encodeFormula φ).length := by
  induction φ generalizing cl l with
  | nil =>
      cases hcl
  | cons c cs ih =>
      rcases List.mem_append.mp (by simpa [Formula.toCNF] using hcl) with hleft | hright
      · have hlt := Constraint.toCNF_lit_var_lt_encodeConstraint_length c cl hleft l hl
        rw [Encoding.encodeFormula_length_cons]
        omega
      · have hlt := ih cl hright l hl
        rw [Encoding.encodeFormula_length_cons]
        omega

theorem toCNF_varBound_le_encodeFormula_length {Γ : BoolLanguage} (φ : Formula Γ) :
    SAT.CNF.varBound (Formula.toCNF φ) ≤ (Encoding.encodeFormula φ).length := by
  exact SAT.CNF.varBound_le_of_vars_lt (Formula.toCNF φ) (Encoding.encodeFormula φ).length
    (toCNF_lit_var_lt_encodeFormula_length φ)

/-- Structural CNF size is linearly bounded by source encoding length for fixed finite `Γ`. -/
theorem toCNF_structuralSize_le_general {Γ : BoolLanguage} (φ : Formula Γ) :
    SAT.CNF.structuralSize (Formula.toCNF φ) ≤
      (1 + Γ.maxFalsifyingTuples * Γ.maxArity + Γ.maxFalsifyingTuples) *
        (Encoding.encodeFormula φ).length + 1 := by
  have hvar := toCNF_varBound_le_encodeFormula_length φ
  have htotal := toCNF_totalClauseLength_le_general φ
  have hlen := toCNF_length_le_general φ
  unfold SAT.CNF.structuralSize
  calc
    SAT.CNF.varBound (Formula.toCNF φ) +
          SAT.CNF.totalClauseLength (Formula.toCNF φ) + (Formula.toCNF φ).length + 1
        ≤ (Encoding.encodeFormula φ).length +
            (Γ.maxFalsifyingTuples * Γ.maxArity) * (Encoding.encodeFormula φ).length +
            Γ.maxFalsifyingTuples * (Encoding.encodeFormula φ).length + 1 := by
      omega
    _ = (1 + Γ.maxFalsifyingTuples * Γ.maxArity + Γ.maxFalsifyingTuples) *
          (Encoding.encodeFormula φ).length + 1 := by
      ring

theorem add_one_sq_le_four_sq_add_one (n : Nat) :
    (n + 1) ^ 2 ≤ 4 * n ^ 2 + 1 := by
  cases n with
  | zero =>
      simp
  | succ k =>
      have hbase : Nat.succ k + 1 ≤ 2 * Nat.succ k := by omega
      have hsquare := Nat.pow_le_pow_left hbase 2
      calc
        (Nat.succ k + 1) ^ 2 ≤ (2 * Nat.succ k) ^ 2 := hsquare
        _ = 2 ^ 2 * (Nat.succ k) ^ 2 := Nat.mul_pow 2 (Nat.succ k) 2
        _ = 4 * (Nat.succ k) ^ 2 := by simp
        _ ≤ 4 * (Nat.succ k) ^ 2 + 1 := by omega

/-- Generic unrestricted-arity encoded output bound for fixed finite Boolean CSP languages. -/
theorem toThreeCNFGeneral_encodedLength_le {Γ : BoolLanguage} (φ : Formula Γ) :
    (SAT.ThreeSATEncoding.encodeThreeCNF (Formula.toThreeCNFGeneral φ)).length ≤
      (20 * (1 + Γ.maxFalsifyingTuples * Γ.maxArity + Γ.maxFalsifyingTuples) ^ 2 * 4) *
        (Encoding.encodeFormula φ).length ^ 2 +
      (20 * (1 + Γ.maxFalsifyingTuples * Γ.maxArity + Γ.maxFalsifyingTuples) ^ 2) := by
  let n := (Encoding.encodeFormula φ).length
  let B := 1 + Γ.maxFalsifyingTuples * Γ.maxArity + Γ.maxFalsifyingTuples
  let S := SAT.CNF.structuralSize (Formula.toCNF φ)
  have hSplit :
      (SAT.ThreeSATEncoding.encodeThreeCNF (Formula.toThreeCNFGeneral φ)).length ≤
        20 * S ^ 2 := by
    simpa [Formula.toThreeCNFGeneral, S] using
      SAT.CNF.splitToThreeCNF_encodedLength_le_quadraticStructural (Formula.toCNF φ)
  have hStruct : S ≤ B * n + 1 := by
    simpa [S, B, n] using toCNF_structuralSize_le_general φ
  have hS2 : S ^ 2 ≤ (B * n + 1) ^ 2 := Nat.pow_le_pow_left hStruct 2
  have hBpos : 1 ≤ B := by
    unfold B
    omega
  have hlin : B * n + 1 ≤ B * (n + 1) := by
    rw [Nat.mul_succ]
    omega
  have hlin2 : (B * n + 1) ^ 2 ≤ (B * (n + 1)) ^ 2 :=
    Nat.pow_le_pow_left hlin 2
  have hn := add_one_sq_le_four_sq_add_one n
  calc
    (SAT.ThreeSATEncoding.encodeThreeCNF (Formula.toThreeCNFGeneral φ)).length
        ≤ 20 * S ^ 2 := hSplit
    _ ≤ 20 * (B * n + 1) ^ 2 := Nat.mul_le_mul_left 20 hS2
    _ ≤ 20 * (B * (n + 1)) ^ 2 := Nat.mul_le_mul_left 20 hlin2
    _ = 20 * (B ^ 2 * (n + 1) ^ 2) := by rw [Nat.mul_pow]
    _ ≤ 20 * (B ^ 2 * (4 * n ^ 2 + 1)) := by
      exact Nat.mul_le_mul_left 20 (Nat.mul_le_mul_left (B ^ 2) hn)
    _ = (20 * B ^ 2 * 4) * n ^ 2 + (20 * B ^ 2) := by ring
    _ = (20 * (1 + Γ.maxFalsifyingTuples * Γ.maxArity + Γ.maxFalsifyingTuples) ^ 2 * 4) *
          (Encoding.encodeFormula φ).length ^ 2 +
        (20 * (1 + Γ.maxFalsifyingTuples * Γ.maxArity + Γ.maxFalsifyingTuples) ^ 2) := by
      simp [B, n]

theorem toThreeCNFGeneral_polynomialSizeBound (Γ : BoolLanguage) :
    PolynomialSizeBound
      (fun φ : Formula Γ => (boolCSPDecisionProblem Γ).Instance.inputSize φ)
      (fun ψ : SAT.ThreeCNF => SAT.threeSATDecisionProblem.Instance.inputSize ψ)
      (fun φ => Formula.toThreeCNFGeneral φ) :=
  PolynomialSizeBound.intro_with 2
    (20 * (1 + Γ.maxFalsifyingTuples * Γ.maxArity + Γ.maxFalsifyingTuples) ^ 2 * 4)
    (20 * (1 + Γ.maxFalsifyingTuples * Γ.maxArity + Γ.maxFalsifyingTuples) ^ 2) (by
      intro φ
      simpa [EncodedType.inputSize, boolCSPDecisionProblem, boolCSPSatLike,
        formulaEncodedType, SAT.threeSATDecisionProblem, SAT.threeSATSatLike,
        SAT.threeCNFEncodedType]
        using toThreeCNFGeneral_encodedLength_le φ)

end Formula

/-- The arity-3 Boolean-CSP-to-3SAT reduction with a project-local costed certificate. -/
noncomputable def boolCSPToThreeSATCostedReduction {Γ : BoolLanguage}
    (hΓ : Γ.IsThreeBounded) :
    CostedReduction (boolCSPDecisionProblem Γ) SAT.threeSATDecisionProblem :=
  CostedReduction.ofCostedMap
    (fun φ => Formula.toThreeCNF hΓ φ)
    (boolCSPToThreeSATReduction hΓ).correct
    (CostedMap.of_encodedLinearSizeBound (Formula.toThreeCNF_linearSizeBound hΓ))

/-- Karp reduction over the project-local costed polynomial-time model. -/
noncomputable def boolCSPToThreeSATKarpReduction {Γ : BoolLanguage}
    (hΓ : Γ.IsThreeBounded) :
    KarpReductionM CostedPolyTimeModel (boolCSPDecisionProblem Γ) SAT.threeSATDecisionProblem :=
  (boolCSPToThreeSATCostedReduction hΓ).toKarpReductionM

/-- The unrestricted-arity Boolean-CSP-to-3SAT reduction with a generic costed certificate. -/
noncomputable def boolCSPToThreeSATGeneralCostedReduction (Γ : BoolLanguage) :
    CostedReduction (boolCSPDecisionProblem Γ) SAT.threeSATDecisionProblem :=
  CostedReduction.ofCostedMap
    (fun φ => Formula.toThreeCNFGeneral φ)
    (boolCSPToThreeSATGeneralReduction Γ).correct
    (CostedMap.of_encodedPolynomialSizeBound (Formula.toThreeCNFGeneral_polynomialSizeBound Γ))

/-- Generic unrestricted-arity Karp reduction over the project-local costed model. -/
noncomputable def boolCSPToThreeSATGeneralKarpReduction (Γ : BoolLanguage) :
    KarpReductionM CostedPolyTimeModel (boolCSPDecisionProblem Γ) SAT.threeSATDecisionProblem :=
  (boolCSPToThreeSATGeneralCostedReduction Γ).toKarpReductionM

end CSP
end ComplexityReduction
