/-
Copyright (c) 2026.
Released under Apache 2.0 license as described in the file LICENSE.
-/

import Mathlib.Data.Finset.Dedup
import Mathlib.Data.List.OfFn
import ComplexityReduction.Legacy.ComplexityReduction.CSP.Formula
import ComplexityReduction.Legacy.ComplexityReduction.SAT.CNF

/-!
Expansion of Boolean CSP constraints to CNF blocks.

For a fixed constraint, each falsifying tuple yields one clause that excludes
exactly that tuple. Because the local MVP only targets languages of arity at
most three, these blocks already fit the local 3SAT target.
-/

namespace ComplexityReduction
namespace CSP

open SAT

/-- A literal that excludes one coordinate of one tuple. -/
def literalForTuple {k : Nat} (vars : Fin k → Nat) (t : BoolTuple k) (i : Fin k) :
    Literal :=
  { var := vars i, neg := t i }

/-- The clause excluding one tuple. -/
def clauseForTuple {k : Nat} (vars : Fin k → Nat) (t : BoolTuple k) : Clause :=
  List.ofFn (fun i : Fin k => literalForTuple vars t i)

@[simp]
theorem literalForTuple_eval_true_iff {k : Nat} (vars : Fin k → Nat)
    (t : BoolTuple k) (a : Assignment) (i : Fin k) :
    Literal.eval (literalForTuple vars t i) a = true ↔ a (vars i) ≠ t i := by
  cases hti : t i <;> simp [literalForTuple, Literal.eval, hti]

@[simp]
theorem clauseForTuple_satisfies_iff {k : Nat} (vars : Fin k → Nat)
    (t : BoolTuple k) (a : Assignment) :
    SAT.Clause.Satisfies (clauseForTuple vars t) a ↔ ∃ i : Fin k, a (vars i) ≠ t i := by
  constructor
  · intro h
    rcases h with ⟨l, hl, hlSat⟩
    rcases (List.mem_ofFn' (fun i : Fin k => literalForTuple vars t i) l).1 hl with ⟨i, rfl⟩
    exact ⟨i, (literalForTuple_eval_true_iff vars t a i).mp hlSat⟩
  · rintro ⟨i, hi⟩
    refine
      ⟨ literalForTuple vars t i
      , (List.mem_ofFn' (fun j : Fin k => literalForTuple vars t j)
          (literalForTuple vars t i)).2 ⟨i, rfl⟩
      , ?_ ⟩
    exact (literalForTuple_eval_true_iff vars t a i).mpr hi

/-- The CNF block generated by one constraint. -/
noncomputable def Constraint.toCNF {Γ : BoolLanguage} (c : Constraint Γ) : CNF :=
  (c.relation.falsifyingTuples.toList).map (fun t => clauseForTuple c.vars t)

@[simp]
theorem Constraint.toCNF_clauseBound {Γ : BoolLanguage} (hΓ : Γ.IsThreeBounded)
    (c : Constraint Γ) :
    CNF.IsThreeCNF (Constraint.toCNF c) := by
  intro clause hmem
  rcases List.mem_map.1 hmem with ⟨t, ht, rfl⟩
  simpa [clauseForTuple] using hΓ c.symbol

/-- One constraint is satisfied iff every clause in its CNF block is satisfied. -/
theorem Constraint.toCNF_correct {Γ : BoolLanguage} (c : Constraint Γ) (a : Assignment) :
    Constraint.Satisfies c a ↔ SAT.CNF.Satisfies (Constraint.toCNF c) a := by
  constructor
  · intro h clause hmem
    rcases List.mem_map.1 hmem with ⟨t, ht, rfl⟩
    have hneq : ∃ i : Fin c.relation.arity, a (c.vars i) ≠ t i := by
      by_contra hnot
      have hEq : c.assignmentTuple a = t := by
        funext i
        by_contra hEq'
        exact hnot ⟨i, hEq'⟩
      have hacc : t ∈ c.relation.accepts := by
        simpa [Constraint.Satisfies, BoolRel.Holds, Constraint.relation, hEq] using h
      have htFinset : t ∈ c.relation.falsifyingTuples := (Finset.mem_toList.1 ht)
      have hnotacc : t ∉ c.relation.accepts :=
        (BoolRel.mem_falsifyingTuples_iff c.relation t).1 htFinset
      exact hnotacc hacc
    exact (clauseForTuple_satisfies_iff c.vars t a).2 hneq
  · intro h
    by_contra hrel
    have htuple : c.assignmentTuple a ∈ c.relation.falsifyingTuples := by
      exact (BoolRel.mem_falsifyingTuples_iff c.relation _).2 hrel
    have hclause :
        SAT.Clause.Satisfies (clauseForTuple c.vars (c.assignmentTuple a)) a := by
      have hmem : clauseForTuple c.vars (c.assignmentTuple a) ∈ Constraint.toCNF c := by
        exact List.mem_map.mpr ⟨c.assignmentTuple a, Finset.mem_toList.2 htuple, rfl⟩
      exact h (clauseForTuple c.vars (c.assignmentTuple a)) hmem
    have hcontra : ∃ i : Fin c.relation.arity, a (c.vars i) ≠ c.assignmentTuple a i :=
      (clauseForTuple_satisfies_iff c.vars (c.assignmentTuple a) a).1 hclause
    rcases hcontra with ⟨i, hi⟩
    exact hi rfl

/-- A full formula is translated by concatenating its constraint blocks. -/
noncomputable def Formula.toCNF {Γ : BoolLanguage} : Formula Γ → CNF
  | [] => []
  | c :: φ => Constraint.toCNF c ++ Formula.toCNF φ

@[simp]
theorem Formula.toCNF_nil {Γ : BoolLanguage} :
    Formula.toCNF ([] : Formula Γ) = [] :=
  rfl

@[simp]
theorem Formula.toCNF_cons {Γ : BoolLanguage} (c : Constraint Γ) (φ : Formula Γ) :
    Formula.toCNF (c :: φ) = Constraint.toCNF c ++ Formula.toCNF φ :=
  rfl

/-- The CNF produced from a formula is already 3CNF when the language is 3-bounded. -/
theorem Formula.toCNF_clauseBound {Γ : BoolLanguage} (hΓ : Γ.IsThreeBounded)
    (φ : Formula Γ) :
    CNF.IsThreeCNF (Formula.toCNF φ) := by
  induction φ with
  | nil =>
      simp [Formula.toCNF, SAT.CNF.IsThreeCNF]
  | cons c cs ih =>
      intro clause hmem
      rcases List.mem_append.mp hmem with hleft | hright
      · exact Constraint.toCNF_clauseBound hΓ c clause hleft
      · exact ih clause hright

/-- A formula is satisfied iff its CNF translation is satisfied. -/
theorem Formula.toCNF_correct {Γ : BoolLanguage} (φ : Formula Γ) (a : Assignment) :
    Formula.Satisfies φ a ↔ SAT.CNF.Satisfies (Formula.toCNF φ) a := by
  induction φ with
  | nil =>
      simp [Formula.toCNF, Formula.Satisfies, SAT.CNF.Satisfies]
  | cons c cs ih =>
      constructor
      · intro h clause hmem
        rcases List.mem_append.mp hmem with hleft | hright
        · have hc : Constraint.Satisfies c a := h c List.mem_cons_self
          exact (Constraint.toCNF_correct c a).1 hc clause hleft
        · have hcs : Formula.Satisfies cs a := by
            intro d hd
            exact h d (List.mem_cons_of_mem c hd)
          exact ih.1 hcs clause hright
      · intro h d hd
        rcases List.mem_cons.mp hd with hdc | hdcs
        · subst d
          have hc : SAT.CNF.Satisfies (Constraint.toCNF c) a := by
            intro clause hmem
            exact h clause (List.mem_append.mpr (Or.inl hmem))
          exact (Constraint.toCNF_correct c a).2 hc
        · have hcs : SAT.CNF.Satisfies (Formula.toCNF cs) a := by
            intro clause hmem
            exact h clause (List.mem_append.mpr (Or.inr hmem))
          exact ih.2 hcs d hdcs

/-- Formula-level satisfiability is preserved by the CNF expansion. -/
theorem Formula.toCNF_satisfiable_iff {Γ : BoolLanguage} (φ : Formula Γ) :
    SAT.CNF.Satisfiable (Formula.toCNF φ) ↔ Formula.Satisfiable φ := by
  constructor
  · rintro ⟨a, h⟩
    exact ⟨a, (Formula.toCNF_correct φ a).2 h⟩
  · rintro ⟨a, h⟩
    exact ⟨a, (Formula.toCNF_correct φ a).1 h⟩

end CSP
end ComplexityReduction
